services:
  certiflow-app:
    build:
      context: ./CertiFlowApp
    container_name: certiflow-app
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - web
      - certiflow_internal
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.http.routers.certiflow.rule=Host(`certiflow.sarasjodin.se`)"
      - "traefik.http.routers.certiflow.entrypoints=websecure"
      - "traefik.http.routers.certiflow.tls=true"
      - "traefik.http.routers.certiflow.tls.certresolver=myresolver"
      - "traefik.http.services.certiflow.loadbalancer.server.port=8080"
    environment:
      APP_ENVIRONMENTAL_LABEL: "Prod"
      ASPNETCORE_ENVIRONMENT: "Production"
    env_file:
      - .env
    volumes:
      - certiflow_dataprotection_keys:/root/.aspnet/DataProtection-Keys

  db:
    image: postgres:16
    container_name: certiflow-db
    restart: unless-stopped
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - certiflow_internal

networks:
  web:
    external: true
  certiflow_internal:
    driver: bridge

volumes:
  certiflow_dataprotection_keys:
