services:
  certiflow-placeholder:
    image: traefik/whoami
    container_name: certiflow-placeholder
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.certiflow.rule=Host(`certiflow.sarasjodin.se`)"
      - "traefik.http.routers.certiflow.entrypoints=websecure"
      - "traefik.http.routers.certiflow.tls=true"
      - "traefik.http.routers.certiflow.tls.certresolver=myresolver"
      - "traefik.http.services.certiflow.loadbalancer.server.port=80"

networks:
  web:
    external: true
